Added support for the identification of redundant gene groups, necessary for the eventual production of canonical interactor information.

diff --git a/scripts/irbuild b/scripts/irbuild
--- a/scripts/irbuild
+++ b/scripts/irbuild
@@ -81,6 +81,13 @@ fi
 
 if [ "$BUILD" ]; then
 
+    # Make canonical interactor information.
+
+    if ! "$SCRIPTS/ircanonical" ; then
+        echo "$PROGNAME: Did not make canonical information." 1>&2
+        exit 1
+    fi
+
     # Assign definitive sequence information to interactors.
 
     if ! "$TOOLS/irdata_database_action.py" "$DATABASE" "$SQL/import_irefindex_assignments.sql" ; then
@@ -159,7 +166,7 @@ if [ "$BUILD" ]; then
     # Make convenient representations for other entity types.
 
     if ! "$TOOLS/irdata_database_action.py" "$DATABASE" "$SQL/import_irefindex_interactions.sql" ; then
-        echo "$PROGNAME: Could not build interactor information from the imported data." 1>&2
+        echo "$PROGNAME: Could not build interaction information from the imported data." 1>&2
         exit 1
     fi
 fi
diff --git a/scripts/irinit b/scripts/irinit
--- a/scripts/irinit
+++ b/scripts/irinit
@@ -41,6 +41,11 @@ if ! "$TOOLS/irdata_database_action.py" "$DATABASE" "$SQL/init_irefindex_interac
     exit 1
 fi
 
+if ! "$TOOLS/irdata_database_action.py" "$DATABASE" "$SQL/init_irefindex_canonical.sql" ; then
+    echo "$PROGNAME: Could not initialise the canonical interactor information schema." 1>&2
+    exit 1
+fi
+
 if ! "$TOOLS/irdata_database_action.py" "$DATABASE" "$SQL/init_irefindex_assignments.sql" ; then
     echo "$PROGNAME: Could not initialise the assignment information schema." 1>&2
     exit 1
