Added various steps to the build script, providing control over the missing interactor retrieval activities.

diff --git a/scripts/irbuild b/scripts/irbuild
--- a/scripts/irbuild
+++ b/scripts/irbuild
@@ -10,37 +10,88 @@ fi
 
 if [ "$1" = '--help' ] || [ "$1" != '--build' ]; then
     cat 1>&2 <<EOF
-Usage: $PROGNAME --build
+Usage: $PROGNAME --build [ --no-download ] [ --reports ]
 
 Build interactor and assignment information from the imported source data.
 EOF
     exit 1
 fi
 
+BUILD=$1
+shift 1
+
+if [ "$1" = '--no-download' ]; then
+    MISSING_OPTIONS='--import'
+    shift 1
+else
+    MISSING_OPTIONS='--all'
+fi
+
+if [ "$1" = '--reports' ]; then
+    MAKE_REPORTS=$1
+    shift 1
+fi
+
+# Convert MITAB-based data to an XML-compatible representation.
+
 if ! "$TOOLS/irdata_database_action.py" "$DATABASE" "$SQL/mitab_to_xml.sql" ; then
     echo "$PROGNAME: Could not convert MITAB data to the common data representation." 1>&2
     exit 1
 fi
+
+# Finalise the XML-based data.
 
 if ! "$TOOLS/irdata_database_action.py" "$DATABASE" "$SQL/import_irefindex_constraints.sql" ; then
     echo "$PROGNAME: Constraints could not be applied to the common data representation." 1>&2
     exit 1
 fi
 
+# Identify the interactors.
+
 if ! "$TOOLS/irdata_database_action.py" "$DATABASE" "$SQL/import_irefindex_interactors.sql" ; then
     echo "$PROGNAME: Could not build interactor information from the imported data." 1>&2
     exit 1
 fi
 
-if ! "$SCRIPTS/irmissing" ; then
+# Add missing interactor information.
+
+if ! "$SCRIPTS/irmissing" $MISSING_OPTIONS ; then
     echo "$PROGNAME: Did not retrieve missing/unknown sequences." 1>&2
     exit 1
 fi
+
+if [ "$MAKE_REPORTS" ]; then
+
+    # Make an interactor report, if requested.
+
+    if ! "$TOOLS/irdata_database_action.py" "$DATABASE" "$REPORTS/interactors_by_source.sql" ; then
+        echo "$PROGNAME: Could not report source interactor information." 1>&2
+        exit 1
+    fi
+fi
+
+# Assign definitive sequence information to interactors.
 
 if ! "$TOOLS/irdata_database_action.py" "$DATABASE" "$SQL/import_irefindex_assignments.sql" ; then
     echo "$PROGNAME: Could not build assignment information from the imported data." 1>&2
     exit 1
 fi
+
+if [ "$MAKE_REPORTS" ]; then
+
+    # Make assigned interactor reports, if requested.
+
+    if ! "$TOOLS/irdata_database_action.py" "$DATABASE" "$REPORTS/assignments_by_source.sql" ; then
+        echo "$PROGNAME: Could not report sequence assignment information." 1>&2
+        exit 1
+    fi
+    if ! "$TOOLS/irdata_database_action.py" "$DATABASE" "$REPORTS/rogids_by_source.sql" ; then
+        echo "$PROGNAME: Could not report ROG identifier assignment information." 1>&2
+        exit 1
+    fi
+fi
+
+# Export ROG information for RIG identifier calculation, make and import RIG identifiers.
 
 if ! "$TOOLS/irdata_database_action.py" "$DATABASE" "$SQL/export_irefindex_rogids.sql" ; then
     echo "$PROGNAME: Could not export ROG identifiers for assigned sequences." 1>&2
@@ -54,5 +105,22 @@ fi
 
 if ! "$TOOLS/irdata_database_action.py" "$DATABASE" "$SQL/import_irefindex_rigids.sql" ; then
     echo "$PROGNAME: Could not import the generated RIG identifiers." 1>&2
+    exit 1
+fi
+
+if [ "$MAKE_REPORTS" ]; then
+
+    # Make an interactions report, if requested.
+
+    if ! "$TOOLS/irdata_database_action.py" "$DATABASE" "$REPORTS/rigids_by_source.sql" ; then
+        echo "$PROGNAME: Could not report RIG identifier assignment information." 1>&2
+        exit 1
+    fi
+fi
+
+# Make convenient representations for other entity types.
+
+if ! "$TOOLS/irdata_database_action.py" "$DATABASE" "$SQL/import_irefindex_interactions.sql" ; then
+    echo "$PROGNAME: Could not build interactor information from the imported data." 1>&2
     exit 1
 fi
