Integrated integer identifier import into the build script. Added notes on the integer identifier data to the documentation.

diff --git a/scripts/irbuild b/scripts/irbuild
--- a/scripts/irbuild
+++ b/scripts/irbuild
@@ -203,6 +203,13 @@ if [ "$BUILD" ]; then
         echo "$PROGNAME: Could not build participant information from the imported data." 1>&2
         exit 1
     fi
+
+    # Import integer identifiers from a previous release.
+
+    if [[ -e "$DATA/rig2rigid" && -e "$DATA/rog2rogid" ]] && ! "$TOOLS/irdata_database_action.py" "$DATABASE" "$SQL/import_irefindex_integer_identifiers.sql" "$DATA" ; then
+        echo "$PROGNAME: Could not import integer identifiers from the previous release." 1>&2
+        exit 1
+    fi
 fi
 
 if [ "$MAKE_OUTPUT" ]; then
