Separated identifier matching and the resulting interactor-to-sequence mapping construction from the initial interactor identification. Made the identifier matching template configurable so that it can be used with both current and archived sequence information. Removed the refdate column from various tables since sequence record dates are not currently being used. Added sequence schema initialisation to the irinit script. Changed the Y-scoring to look for sequencelink values of a different form.

diff --git a/scripts/irbuild b/scripts/irbuild
--- a/scripts/irbuild
+++ b/scripts/irbuild
@@ -84,6 +84,27 @@ if [ "$BUILD" ]; then
         exit 1
     fi
 
+    # Map identifiers to sequences in current databases.
+
+    if ! "$TOOLS/irdata_database_action.py" "$DATABASE" "$SQL/import_irefindex_identifier_sequences.sql" --defs sequences irefindex_sequences linkprefix '' ; then
+        echo "$PROGNAME: Could not build interactor information from the imported data." 1>&2
+        exit 1
+    fi
+
+    # Map identifiers to sequences in archived databases.
+
+    if ! "$TOOLS/irdata_database_action.py" "$DATABASE" "$SQL/import_irefindex_identifier_sequences.sql" --defs sequences irefindex_sequences_archived linkprefix 'archived/' ; then
+        echo "$PROGNAME: Could not build interactor information from the imported data." 1>&2
+        exit 1
+    fi
+
+    # Map interactors to sequences.
+
+    if ! "$TOOLS/irdata_database_action.py" "$DATABASE" "$SQL/import_irefindex_interactor_sequences.sql" ; then
+        echo "$PROGNAME: Could not map interactors to sequences." 1>&2
+        exit 1
+    fi
+
     # Add missing interactor information.
 
     if ! "$SCRIPTS/irmissing" $MISSING_OPTIONS ; then
@@ -108,7 +129,7 @@ if [ "$BUILD" ]; then
 
     # Make canonical interactor information.
 
-    if ! "$SCRIPTS/ircanonical" ; then
+    if ! "$SCRIPTS/ircanonical" --build ; then
         echo "$PROGNAME: Did not make canonical information." 1>&2
         exit 1
     fi
diff --git a/scripts/irinit b/scripts/irinit
--- a/scripts/irinit
+++ b/scripts/irinit
@@ -36,6 +36,16 @@ for SOURCE in $ALLSOURCES ; do
     fi
 done
 
+if ! "$TOOLS/irdata_database_action.py" "$DATABASE" "$SQL/init_irefindex_sequences.sql" ; then
+    echo "$PROGNAME: Could not initialise the consolidated sequence information schema." 1>&2
+    exit 1
+fi
+
+if ! "$TOOLS/irdata_database_action.py" "$DATABASE" "$SQL/init_irefindex_archived.sql" ; then
+    echo "$PROGNAME: Could not initialise the archived sequence information schema." 1>&2
+    exit 1
+fi
+
 if ! "$TOOLS/irdata_database_action.py" "$DATABASE" "$SQL/init_irefindex_interactors.sql" ; then
     echo "$PROGNAME: Could not initialise the interactor information schema." 1>&2
     exit 1
