Renamed templates and tables so that "obsolete" data is now known as "archived" data, since a more comprehensive data set is required for obsolete identifier matching. Introduced the use of archived data in the identifier matching process. Added obsolete data scoring to the assignments template.

diff --git a/scripts/irbuild b/scripts/irbuild
--- a/scripts/irbuild
+++ b/scripts/irbuild
@@ -63,10 +63,10 @@ if [ "$BUILD" ]; then
         exit 1
     fi
 
-    # Import obsolete identifiers from a previous release.
+    # Import archived identifiers from a previous release.
 
-    if [ -e "$DATA/obsolete" ] && ! "$TOOLS/irdata_database_action.py" "$DATABASE" "$SQL/import_irefindex_obsolete.sql" "$DATA" ; then
-        echo "$PROGNAME: Could not import obsolete identifiers from the previous release." 1>&2
+    if [ -e "$DATA/sequences_archived" ] && ! "$TOOLS/irdata_database_action.py" "$DATABASE" "$SQL/import_irefindex_archived.sql" "$DATA" ; then
+        echo "$PROGNAME: Could not import archived identifiers from the previous release." 1>&2
         exit 1
     fi
 
diff --git a/scripts/irprevious b/scripts/irprevious
--- a/scripts/irprevious
+++ b/scripts/irprevious
@@ -50,10 +50,10 @@ if [ "$PGSQL" ]; then
         exit 1
     fi
 
-    # Export obsolete identifiers from a PostgreSQL database.
+    # Export archived identifiers from a PostgreSQL database.
 
-    if ! "$TOOLS/irdata_database_action.py" "$DATABASE" "$SQL/export_irefindex_obsolete.sql" "$DATA" ; then
-        echo "$PROGNAME: Could not export obsolete identifiers from the previous database." 1>&2
+    if ! "$TOOLS/irdata_database_action.py" "$DATABASE" "$SQL/export_irefindex_archived.sql" "$DATA" ; then
+        echo "$PROGNAME: Could not export archived identifiers from the previous database." 1>&2
         exit 1
     fi
 
@@ -61,20 +61,20 @@ elif [ "$MYSQL" ]; then
 
     # Export identifiers from a MySQL database.
 
-    if ! mysql $OPTIONS < "$SQL/mysql/export_irefindex_integer_rigids.sql" > "$DATA/rig2rigid" ; then
+    if ! mysql -N $OPTIONS < "$SQL/mysql/export_irefindex_integer_rigids.sql" > "$DATA/rig2rigid" ; then
         echo "$PROGNAME: Could not export integer RIG identifiers from the previous database." 1>&2
         exit 1
     fi
 
-    if ! mysql $OPTIONS < "$SQL/mysql/export_irefindex_integer_rogids.sql" > "$DATA/rog2rogid" ; then
+    if ! mysql -N $OPTIONS < "$SQL/mysql/export_irefindex_integer_rogids.sql" > "$DATA/rog2rogid" ; then
         echo "$PROGNAME: Could not export integer ROG identifiers from the previous database." 1>&2
         exit 1
     fi
 
-    # Export obsolete identifiers from a MySQL database.
+    # Export archived identifiers from a MySQL database.
 
-    if ! mysql $OPTIONS < "$SQL/mysql/export_irefindex_obsolete.sql" > "$DATA/obsolete" ; then
-        echo "$PROGNAME: Could not export obsolete identifiers from the previous database." 1>&2
+    if ! mysql -N $OPTIONS < "$SQL/mysql/export_irefindex_archived.sql" > "$DATA/sequences_archived" ; then
+        echo "$PROGNAME: Could not export archived identifiers from the previous database." 1>&2
         exit 1
     fi
 fi
