Moved the gene-to-protein mapping operations into separate templates.

diff --git a/scripts/irbuild b/scripts/irbuild
--- a/scripts/irbuild
+++ b/scripts/irbuild
@@ -106,17 +106,24 @@ if [ "$BUILD" ]; then
         exit 1
     fi
 
+    # Establish gene-to-protein mappings.
+
+    if ! "$TOOLS/irdata_database_action.py" "$DATABASE" "$SQL/import_irefindex_gene_mappings.sql" ; then
+        echo "$PROGNAME: Could not create gene-to-protein mappings." 1>&2
+        exit 1
+    fi
+
     # Map identifiers to sequences in current databases.
 
     if ! "$TOOLS/irdata_database_action.py" "$DATABASE" "$SQL/import_irefindex_identifier_sequences.sql" --defs sequences irefindex_sequences linkprefix '' ; then
-        echo "$PROGNAME: Could not build interactor information from the imported data." 1>&2
+        echo "$PROGNAME: Could not build sequence information from the imported data." 1>&2
         exit 1
     fi
 
     # Map identifiers to sequences in archived databases.
 
     if ! "$TOOLS/irdata_database_action.py" "$DATABASE" "$SQL/import_irefindex_identifier_sequences.sql" --defs sequences irefindex_sequences_archived linkprefix 'archived/' ; then
-        echo "$PROGNAME: Could not build interactor information from the imported data." 1>&2
+        echo "$PROGNAME: Could not build sequence information from archived data." 1>&2
         exit 1
     fi
 
diff --git a/scripts/irdrop b/scripts/irdrop
--- a/scripts/irdrop
+++ b/scripts/irdrop
@@ -71,6 +71,11 @@ if ! "$TOOLS/irdata_database_action.py" "$DATABASE" "$SQL/drop_irefindex_interac
     exit 1
 fi
 
+if ! "$TOOLS/irdata_database_action.py" "$DATABASE" "$SQL/drop_irefindex_gene_mappings.sql" ; then
+    echo "$PROGNAME: Could not remove the gene-to-protein mappings schema." 1>&2
+    exit 1
+fi
+
 if ! "$TOOLS/irdata_database_action.py" "$DATABASE" "$SQL/drop_irefindex_canonical.sql" ; then
     echo "$PROGNAME: Could not remove the canonical interactor information schema." 1>&2
     exit 1
