Added a variable indicating the location of the reports.

diff --git a/scripts/irdata-config b/scripts/irdata-config
--- a/scripts/irdata-config
+++ b/scripts/irdata-config
@@ -63,6 +63,17 @@ else
     exit 1
 fi
 
+SYSREPORTS="$SYSPREFIX/usr/share/irdata/reports"
+
+if [ -e "$SCRIPTS/../reports" ]; then
+    REPORTS=`normpath "$SCRIPTS/../reports"`
+elif [ -e "$SYSREPORTS" ]; then
+    REPORTS="$SYSREPORTS"
+else
+    echo "Cannot locate the irdata reports directory." 1>&2
+    exit 1
+fi
+
 # Data directory.
 
 SYSDATA="$SYSPREFIX/var/lib/irdata/data"
