Added some failure reporting and exit status signalling to the download and manifest scripts. Added exception handling to the manifest parsing tool. Removed superfluous $"..." string usage.

diff --git a/scripts/irdownload b/scripts/irdownload
--- a/scripts/irdownload
+++ b/scripts/irdownload
@@ -46,6 +46,8 @@ fi
 
 # Download data.
 
+FAILED=
+
 for SOURCE in $SOURCES; do
     eval DOWNLOAD_SCRIPT='$'"$SOURCE"_DOWNLOAD_SCRIPT
     eval RELEASE_URL='$'"$SOURCE"_RELEASE_URL
@@ -67,11 +69,16 @@ for SOURCE in $SOURCES; do
     # even though they could easily do so.
 
     if [ "$DOWNLOAD_SCRIPT" ]; then
-        "$DOWNLOAD_SCRIPT" $CHECK_ONLY $VERBOSE "$DATADIR"
+        if ! "$DOWNLOAD_SCRIPT" $CHECK_ONLY $VERBOSE "$DATADIR" ; then
+            echo "$PROGNAME: Did not download files using the script for source: $SOURCE" 1>&2
+            FAILED="${FAILED}${FAILED:+ }$SOURCE"
+        fi
 
     # Most resources just publish files.
 
     else
+        FAILED_FILES=0
+
         for DOWNLOAD in $DOWNLOAD_FILES; do
             DOWNLOADED="$DATADIR/$DOWNLOAD"
             URL="${RELEASE_URL}$DOWNLOAD"
@@ -96,6 +103,7 @@ for SOURCE in $SOURCES; do
                 echo "$PROGNAME: Downloading file: $DOWNLOAD" 1>&2
                 if ! wget --timestamping --retr-symlinks -N -P "$DATADIR" "$URL" ; then
                     echo "$PROGNAME: Did not download file: $DOWNLOAD" 1>&2
+                    FAILED_FILES=$(($FAILED_FILES+1))
                     continue
                 fi
 
@@ -115,5 +123,15 @@ for SOURCE in $SOURCES; do
                 fi
             fi
         done
+
+        if [ "$FAILED_FILES" != '0' ]; then
+            echo "$PROGNAME: Did not download $FAILED_FILES files for source: $SOURCE" 1>&2
+            FAILED="${FAILED}${FAILED:+ }$SOURCE"
+        fi
     fi
 done
+
+if [ "$FAILED" ]; then
+    echo "$PROGNAME: The following sources failed: $FAILED" 1>&2
+    exit 1
+fi
diff --git a/scripts/irmanifest b/scripts/irmanifest
--- a/scripts/irmanifest
+++ b/scripts/irmanifest
@@ -8,14 +8,21 @@ else
     . 'irdata-config'
 fi
 
+MANIFEST_OUTPUT="$DATA/irefindex_manifest"
+
 if [ "$1" = '--help' ]; then
     cat 1>&2 <<EOF
 Usage: $PROGNAME ( <source>... | --all )
 
-Display a manifest of source data releases. If --all is specified, the following
+Create a manifest of source data releases. If --all is specified, the following
 sources will be inspected:
 
 $ALLSOURCES
+
+Specifying --all will create a new manifest file. Specifying individual sources
+will append manifest entries to any existing file in the following location:
+
+$MANIFEST_OUTPUT
 EOF
     exit 1
 fi
@@ -25,6 +32,12 @@ if [ ! "$1" ]; then
     exit 1
 elif [ "$1" = '--all' ]; then
     SOURCES="$ALLSOURCES"
+
+    # Remove any existing output if it exists.
+
+    if [ -e "$MANIFEST_OUTPUT" ]; then
+        rm "$MANIFEST_OUTPUT"
+    fi
 else
     SOURCES=$*
 fi
@@ -78,8 +91,22 @@ fi
       fi
 
   done \
-> "$DATA/irefindex_manifest"
+>> "$MANIFEST_OUTPUT"
 
 # Make the date formats available for import.
 
 cp "$MANIFESTS/dateformats.txt" "$DATA"
+
+# Report any failed manifests.
+
+FAILED=
+for SOURCE in $SOURCES ; do
+    if ! grep -e "^$SOURCE"$'\t' "$MANIFEST_OUTPUT" > /dev/null 2>&1 ; then
+        FAILED="${FAILED}${FAILED:+ }$SOURCE"
+    fi
+done
+
+if [ "$FAILED" ]; then
+    echo "$PROGNAME: Manifest generation failed for sources: $FAILED"
+    exit 1
+fi
