Added a force option to the drop script.

diff --git a/scripts/irdrop b/scripts/irdrop
--- a/scripts/irdrop
+++ b/scripts/irdrop
@@ -25,7 +25,7 @@ fi
 
 if [ "$1" = '--help' ] || [ "$1" != '--drop' ]; then
     cat 1>&2 <<EOF
-Usage: $PROGNAME --drop ( --all | --build )
+Usage: $PROGNAME --drop ( --all | --build ) [ -f ]
 
 Remove schema definitions from the database.
 EOF
@@ -41,6 +41,12 @@ elif [ "$1" = '--build' ]; then
 else
     echo "$PROGNAME: Either --all or --build must be given." 1>&2
     exit 1
+fi
+
+shift 1
+
+if [ "$1" = '-f' ]; then
+    FORCE=$1
 fi
 
 # If requested, drop all source data tables.
@@ -70,68 +76,74 @@ if [ "$DROPALL" ]; then
 fi
 
 # Remove the different build tables.
+# Continue without exiting if the force option is given.
 
 if ! "$TOOLS/irdata_database_action.py" "$DATABASE" "$SQL/drop_irefindex_manifest.sql" $PSQL_OPTIONS ; then
     echo "$PROGNAME: Could not remove the manifest schema." 1>&2
-    exit 1
+    [ ! "$FORCE" ] && exit 1
+fi
+
+if [ ! "$DROPALL" ] && ! "$TOOLS/irdata_database_action.py" "$DATABASE" "$SQL/drop_irefindex_constraints.sql" $PSQL_OPTIONS ; then
+    echo "$PROGNAME: Could not remove the common representation's constraints." 1>&2
+    [ ! "$FORCE" ] && exit 1
 fi
 
 if ! "$TOOLS/irdata_database_action.py" "$DATABASE" "$SQL/drop_irefindex_sequences.sql" $PSQL_OPTIONS ; then
     echo "$PROGNAME: Could not remove the consolidated sequence information schema." 1>&2
-    exit 1
+    [ ! "$FORCE" ] && exit 1
 fi
 
 if ! "$TOOLS/irdata_database_action.py" "$DATABASE" "$SQL/drop_irefindex_archived.sql" $PSQL_OPTIONS ; then
     echo "$PROGNAME: Could not remove the archived sequence information schema." 1>&2
-    exit 1
+    [ ! "$FORCE" ] && exit 1
 fi
 
 if ! "$TOOLS/irdata_database_action.py" "$DATABASE" "$SQL/drop_irefindex_interactors.sql" $PSQL_OPTIONS ; then
     echo "$PROGNAME: Could not remove the interactor information schema." 1>&2
-    exit 1
+    [ ! "$FORCE" ] && exit 1
 fi
 
 if ! "$TOOLS/irdata_database_action.py" "$DATABASE" "$SQL/drop_irefindex_gene_mappings.sql" $PSQL_OPTIONS ; then
     echo "$PROGNAME: Could not remove the gene-to-protein mappings schema." 1>&2
-    exit 1
+    [ ! "$FORCE" ] && exit 1
 fi
 
 if ! "$TOOLS/irdata_database_action.py" "$DATABASE" "$SQL/drop_irefindex_canonical.sql" $PSQL_OPTIONS ; then
     echo "$PROGNAME: Could not remove the canonical interactor information schema." 1>&2
-    exit 1
+    [ ! "$FORCE" ] && exit 1
 fi
 
 if ! "$TOOLS/irdata_database_action.py" "$DATABASE" "$SQL/drop_irefindex_assignments.sql" $PSQL_OPTIONS ; then
     echo "$PROGNAME: Could not remove the assignment information schema." 1>&2
-    exit 1
+    [ ! "$FORCE" ] && exit 1
 fi
 
 if ! "$TOOLS/irdata_database_action.py" "$DATABASE" "$SQL/drop_irefindex_rigids.sql" $PSQL_OPTIONS ; then
     echo "$PROGNAME: Could not remove the interaction information schema." 1>&2
-    exit 1
+    [ ! "$FORCE" ] && exit 1
 fi
 
 if ! "$TOOLS/irdata_database_action.py" "$DATABASE" "$SQL/drop_irefindex_integer_identifiers.sql" $PSQL_OPTIONS ; then
     echo "$PROGNAME: Could not remove the integer identifier mappings schema." 1>&2
-    exit 1
+    [ ! "$FORCE" ] && exit 1
 fi
 
 if ! "$TOOLS/irdata_database_action.py" "$DATABASE" "$SQL/drop_irefindex_interactions.sql" $PSQL_OPTIONS ; then
     echo "$PROGNAME: Could not remove the additional interaction information schema." 1>&2
-    exit 1
+    [ ! "$FORCE" ] && exit 1
 fi
 
 if ! "$TOOLS/irdata_database_action.py" "$DATABASE" "$SQL/drop_irefindex_experiments.sql" $PSQL_OPTIONS ; then
     echo "$PROGNAME: Could not remove the additional experiment information schema." 1>&2
-    exit 1
+    [ ! "$FORCE" ] && exit 1
 fi
 
 if ! "$TOOLS/irdata_database_action.py" "$DATABASE" "$SQL/drop_irefindex_participants.sql" $PSQL_OPTIONS ; then
     echo "$PROGNAME: Could not remove the additional participant information schema." 1>&2
-    exit 1
+    [ ! "$FORCE" ] && exit 1
 fi
 
 if ! "$TOOLS/irdata_database_action.py" "$DATABASE" "$SQL/drop_irefindex_confidence.sql" $PSQL_OPTIONS ; then
     echo "$PROGNAME: Could not remove the confidence score schema." 1>&2
-    exit 1
+    [ ! "$FORCE" ] && exit 1
 fi
