Added options to limit database modifications to the build tables.

diff --git a/scripts/irdrop b/scripts/irdrop
--- a/scripts/irdrop
+++ b/scripts/irdrop
@@ -25,36 +25,56 @@ fi
 
 if [ "$1" = '--help' ] || [ "$1" != '--drop' ]; then
     cat 1>&2 <<EOF
-Usage: $PROGNAME --drop
+Usage: $PROGNAME --drop ( --all | --build )
 
 Remove schema definitions from the database.
 EOF
     exit 1
 fi
 
-if ! ( "$TOOLS/irdata_database_action.py" "$DATABASE" "$SQL/drop.sql" $PSQL_OPTIONS \
-    && "$TOOLS/irdata_database_action.py" "$DATABASE" "$SQL/drop_psixml.sql" $PSQL_OPTIONS \
-    && "$TOOLS/irdata_database_action.py" "$DATABASE" "$SQL/drop_mitab.sql" $PSQL_OPTIONS \
-    && "$TOOLS/irdata_database_action.py" "$DATABASE" "$SQL/drop_irefindex_manifest.sql" $PSQL_OPTIONS \
-    ) ; then
-    echo "$PROGNAME: Could not remove the database schema." 1>&2
+shift 1
+
+if [ "$1" = '--all' ]; then
+    DROPALL=$1
+elif [ "$1" = '--build' ]; then
+    DROPBUILD=$1
+else
+    echo "$PROGNAME: Either --all or --build must be given." 1>&2
     exit 1
 fi
 
-# Remove any special schemas for data sources.
+# If requested, drop all source data tables.
 
-for SOURCE in $ALLSOURCES ; do
-    eval SCHEMA='$'"$SOURCE"_SCHEMA
+if [ "$DROPALL" ]; then
 
-    if [ "$SCHEMA" ]; then
-        if ! "$TOOLS/irdata_database_action.py" "$DATABASE" "$SQL/drop_${SCHEMA}.sql" $PSQL_OPTIONS ; then
-            echo "$PROGNAME: Could not remove schema for $SOURCE." 1>&2
-            exit 1
-        fi
+    if ! ( "$TOOLS/irdata_database_action.py" "$DATABASE" "$SQL/drop.sql" $PSQL_OPTIONS \
+        && "$TOOLS/irdata_database_action.py" "$DATABASE" "$SQL/drop_psixml.sql" $PSQL_OPTIONS \
+        && "$TOOLS/irdata_database_action.py" "$DATABASE" "$SQL/drop_mitab.sql" $PSQL_OPTIONS \
+        ) ; then
+        echo "$PROGNAME: Could not remove the database schema." 1>&2
+        exit 1
     fi
-done
+
+    # Remove any special schemas for data sources.
+
+    for SOURCE in $ALLSOURCES ; do
+        eval SCHEMA='$'"$SOURCE"_SCHEMA
+
+        if [ "$SCHEMA" ]; then
+            if ! "$TOOLS/irdata_database_action.py" "$DATABASE" "$SQL/drop_${SCHEMA}.sql" $PSQL_OPTIONS ; then
+                echo "$PROGNAME: Could not remove schema for $SOURCE." 1>&2
+                exit 1
+            fi
+        fi
+    done
+fi
 
 # Remove the different build tables.
+
+if ! "$TOOLS/irdata_database_action.py" "$DATABASE" "$SQL/drop_irefindex_manifest.sql" $PSQL_OPTIONS ; then
+    echo "$PROGNAME: Could not remove the manifest schema." 1>&2
+    exit 1
+fi
 
 if ! "$TOOLS/irdata_database_action.py" "$DATABASE" "$SQL/drop_irefindex_sequences.sql" $PSQL_OPTIONS ; then
     echo "$PROGNAME: Could not remove the consolidated sequence information schema." 1>&2
diff --git a/scripts/irinit b/scripts/irinit
--- a/scripts/irinit
+++ b/scripts/irinit
@@ -25,36 +25,53 @@ fi
 
 if [ "$1" = '--help' ] || [ "$1" != '--init' ]; then
     cat 1>&2 <<EOF
-Usage: $PROGNAME --init
+Usage: $PROGNAME --init [ --build ]
 
 Initialise the system for import and build.
 EOF
     exit 1
 fi
 
-if ! ( "$TOOLS/irdata_database_action.py" "$DATABASE" "$SQL/init.sql" $PSQL_OPTIONS \
-    && "$TOOLS/irdata_database_action.py" "$DATABASE" "$SQL/init_psixml.sql" $PSQL_OPTIONS \
-    && "$TOOLS/irdata_database_action.py" "$DATABASE" "$SQL/init_mitab.sql" $PSQL_OPTIONS \
-    && "$TOOLS/irdata_database_action.py" "$DATABASE" "$SQL/init_irefindex_manifest.sql" $PSQL_OPTIONS \
-    ) ; then
-    echo "$PROGNAME: Could not initialise the database schema." 1>&2
-    exit 1
+shift 1
+
+if [ "$1" = '--build' ]; then
+    INITBUILD=$1
+else
+    INITBUILD=
 fi
 
-# Initialise any special schemas for data sources.
+# Initialise source data tables if the build-only option is not set.
 
-for SOURCE in $ALLSOURCES ; do
-    eval SCHEMA='$'"$SOURCE"_SCHEMA
+if [ ! "$INITBUILD" ]; then
 
-    if [ "$SCHEMA" ]; then
-        if ! "$TOOLS/irdata_database_action.py" "$DATABASE" "$SQL/init_${SCHEMA}.sql" $PSQL_OPTIONS ; then
-            echo "$PROGNAME: Could not initialise schema for $SOURCE." 1>&2
-            exit 1
-        fi
+    if ! ( "$TOOLS/irdata_database_action.py" "$DATABASE" "$SQL/init.sql" $PSQL_OPTIONS \
+        && "$TOOLS/irdata_database_action.py" "$DATABASE" "$SQL/init_psixml.sql" $PSQL_OPTIONS \
+        && "$TOOLS/irdata_database_action.py" "$DATABASE" "$SQL/init_mitab.sql" $PSQL_OPTIONS \
+        ) ; then
+        echo "$PROGNAME: Could not initialise the database schema." 1>&2
+        exit 1
     fi
-done
+
+    # Initialise any special schemas for data sources.
+
+    for SOURCE in $ALLSOURCES ; do
+        eval SCHEMA='$'"$SOURCE"_SCHEMA
+
+        if [ "$SCHEMA" ]; then
+            if ! "$TOOLS/irdata_database_action.py" "$DATABASE" "$SQL/init_${SCHEMA}.sql" $PSQL_OPTIONS ; then
+                echo "$PROGNAME: Could not initialise schema for $SOURCE." 1>&2
+                exit 1
+            fi
+        fi
+    done
+fi
 
 # Initialise the different build tables.
+
+if ! "$TOOLS/irdata_database_action.py" "$DATABASE" "$SQL/init_irefindex_manifest.sql" $PSQL_OPTIONS ; then
+    echo "$PROGNAME: Could not initialise the manifest schema." 1>&2
+    exit 1
+fi
 
 if ! "$TOOLS/irdata_database_action.py" "$DATABASE" "$SQL/init_irefindex_sequences.sql" $PSQL_OPTIONS ; then
     echo "$PROGNAME: Could not initialise the consolidated sequence information schema." 1>&2
