Added a "known" column to the integer identifiers tables to distinguish between identifiers known to the previous release and identifiers introduced in the current release. Added the assignment of integer identifiers to newly introduced RIG and ROG identifiers.

diff --git a/scripts/irinit b/scripts/irinit
--- a/scripts/irinit
+++ b/scripts/irinit
@@ -56,6 +56,11 @@ if ! "$TOOLS/irdata_database_action.py" "$DATABASE" "$SQL/init_irefindex_rigids.
     exit 1
 fi
 
+if ! "$TOOLS/irdata_database_action.py" "$DATABASE" "$SQL/init_irefindex_integer_identifiers.sql" ; then
+    echo "$PROGNAME: Could not initialise the integer identifier mappings schema." 1>&2
+    exit 1
+fi
+
 if ! "$TOOLS/irdata_database_action.py" "$DATABASE" "$SQL/init_irefindex_interactions.sql" ; then
     echo "$PROGNAME: Could not initialise the additional interaction information schema." 1>&2
     exit 1
