Added missing data directory information to the ROG/RIG identifier export/import. Added interaction identifier schema initialisation to the irinit script.

diff --git a/scripts/irinit b/scripts/irinit
--- a/scripts/irinit
+++ b/scripts/irinit
@@ -50,3 +50,8 @@ if ! "$TOOLS/irdata_database_action.py" "$DATABASE" "$SQL/init_irefindex_rigids.
     echo "$PROGNAME: Could not initialise the interaction information schema." 1>&2
     exit 1
 fi
+
+if ! "$TOOLS/irdata_database_action.py" "$DATABASE" "$SQL/init_irefindex_interactions.sql" ; then
+    echo "$PROGNAME: Could not initialise the additional interaction information schema." 1>&2
+    exit 1
+fi
