Added support for exporting and retrieving unknown GenBank identifier (gi) records. Changed the options to the irmissing script to permit testing of the different activities supported by the script. Added gene history usage to the interactor sequence matching template, also testing more thoroughly for gi-format values. Changed the RefSeq schema to use gi as the primary key, since initially unknown gi values' records may be retrieved that lack accession and version information, whereas the gi should always be unique.

diff --git a/scripts/irmissing b/scripts/irmissing
--- a/scripts/irmissing
+++ b/scripts/irmissing
@@ -10,7 +10,7 @@ fi
 
 if [ "$1" = '--help' ]; then
     cat 1>&2 <<EOF
-Usage: $PROGNAME [ --check-only | --download-only ]
+Usage: $PROGNAME --check | --download | --import | --all
 
 Obtain missing data by exporting identifiers that do not correspond to sequence
 information and using the list of identifiers to retrieve available records in
@@ -19,12 +19,24 @@ EOF
     exit 1
 fi
 
-if [ "$1" = '--check-only' ]; then
-    CHECK_ONLY=$1
+if [ "$1" = '--check' ] || [ "$1" = '--all' ] ; then
+    CHECK=$1
     shift 1
-elif [ "$1" = '--download-only' ]; then
-    DOWNLOAD_ONLY=$1
+fi
+
+if [ "$1" = '--download' ] || [ "$1" = '--all' ] ; then
+    DOWNLOAD=$1
     shift 1
+fi
+
+if [ "$1" = '--import' ] || [ "$1" = '--all' ] ; then
+    IMPORT=$1
+    shift 1
+fi
+
+if [ ! "$CHECK" ] && [ ! "$DOWNLOAD" ] && [ ! "$IMPORT" ]; then
+    echo "$PROGNAME: Need to specify an operation or --all." 1>&2
+    exit 1
 fi
 
 DATADIR="$DATA/import/RefSeq.unknown"
@@ -33,27 +45,39 @@ if [ ! -e "$DATADIR" ] ; then
     mkdir "$DATADIR"
 fi
 
-if ! "$TOOLS/irdata_database_action.py" "$DATABASE" "$SQL/export_unknown_refseq.sql" "$DATADIR" ; then
-    echo "$PROGNAME: Could not export identifiers missing sequences." 1>&2
-    exit 1
+if [ "$CHECK" ] ; then
+    if ! "$TOOLS/irdata_database_action.py" "$DATABASE" "$SQL/export_unknown_refseq.sql" "$DATADIR" ; then
+        echo "$PROGNAME: Could not export RefSeq identifiers not providing sequences." 1>&2
+        exit 1
+    fi
+
+    if ! "$TOOLS/irdata_database_action.py" "$DATABASE" "$SQL/export_unknown_gi.sql" "$DATADIR" ; then
+        echo "$PROGNAME: Could not export GenBank identifiers not providing sequences." 1>&2
+        exit 1
+    fi
+
+    # Combine the unknown identifiers.
+
+    cat "$DATADIR/unknown_refseq" "$DATADIR/unknown_gi" > "$DATADIR/unknown_all"
+    RESULT="$DATADIR/unknown_all"
 fi
 
-if [ "$CHECK_ONLY" ]; then
-    echo "$DATADIR/unknown_refseq"
-    exit 0
+if [ "$DOWNLOAD" ] ; then
+    if ! "$TOOLS/irdata_fetch_refseq.sh" "$DATADIR" "$DATADIR/unknown_all" ; then
+        echo "$PROGNAME: No RefSeq sequence records downloaded." 1>&2
+        exit 1
+    fi
+
+    RESULT="$DATADIR/unknown_all.result"
 fi
 
-if ! "$TOOLS/irdata_fetch_refseq.sh" "$DATADIR" "$DATADIR/unknown_refseq" ; then
-    echo "$PROGNAME: No sequence records downloaded." 1>&2
-    exit 1
+if [ "$IMPORT" ] ; then
+    if ! "$TOOLS/irdata_database_action.py" "$DATABASE" "$SQL/import_unknown_refseq.sql" "$DATADIR" ; then
+        echo "$PROGNAME: Could not import missing sequences." 1>&2
+        exit 1
+    fi
+
+    RESULT=
 fi
 
-if [ "$DOWNLOAD_ONLY" ]; then
-    echo "$DATADIR/unknown_refseq.result"
-    exit 0
-fi
-
-if ! "$TOOLS/irdata_database_action.py" "$DATABASE" "$SQL/import_unknown_refseq.sql" "$DATADIR" ; then
-    echo "$PROGNAME: Could not import missing sequences." 1>&2
-    exit 1
-fi
+echo $RESULT
