Added support for producing the protein identifier mapping file.

diff --git a/scripts/iroutput b/scripts/iroutput
--- a/scripts/iroutput
+++ b/scripts/iroutput
@@ -29,28 +29,41 @@ MITAB_ORGANISM_OUTPUT="$DATA/{}.mitab.$DATESTAMP.txt"
 
 if [ "$1" = '--help' ]; then
     cat 1>&2 <<EOF
-Usage: $PROGNAME [ --mitab-only | --irefscape-only ]
+Usage: $PROGNAME [ --mitab ] [ --irefscape ] [ --mapping ]
 
-Generate the complete MITAB output file...
+When --mitab is specified, generate the complete MITAB output file...
 
 $MITAB_COMPLETE_OUTPUT
 
 ...along with organism-specific files.
+
+When --irefscape is specified, generate the iRefScape output file.
+
+When --mapping is specified, generate the protein identifier mapping file.
 EOF
     exit 1
 fi
 
-if [ "$1" = '--mitab-only' ]; then
-    MITAB_ONLY=$1
-elif [ "$1" = '--irefscape-only' ]; then
-    IREFSCAPE_ONLY=$1
+if [ "$1" = '--mitab' ]; then
+    MITAB=$1
+    shift 1
+fi
+
+if [ "$1" = '--irefscape' ]; then
+    IREFSCAPE=$1
+    shift 1
+fi
+
+if [ "$1" = '--mapping' ]; then
+    MAPPING=$1
+    shift 1
 fi
 
 
 
 # Generate the complete MITAB output.
 
-if [ ! "$IREFSCAPE_ONLY" ]; then
+if [ "$MITAB" ]; then
 
     echo $DATESTAMP > "$DATA/mitab_date.txt"
 
@@ -83,11 +96,21 @@ if [ ! "$IREFSCAPE_ONLY" ]; then
 
 fi
 
+# Generate the protein identifier mapping.
 
+if [ "$MAPPING" ]; then
+
+    if ! "$TOOLS/irdata_database_action.py" "$DATABASE" "$SQL/export_protein_identifier_mapping.sql" "$DATA" $PSQL_OPTIONS ; then
+        echo "$PROGNAME: Could not generate mapping file." 1>&2
+        exit 1
+    fi
+
+    gzip -f "$DATA/mappings.txt"
+fi
 
 # Generate the iRefScape output.
 
-if [ ! "$MITAB_ONLY" ]; then
+if [ "$IREFSCAPE" ]; then
 
     if [ ! -e "$DATA/iRefScape" ]; then
         mkdir "$DATA/iRefScape"
